### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by dima-online** [heyvaldemar/wikijs-traefik-letsencrypt-docker-compose#1]
1) I would like to get an installation option using custom CA certificates for internal wiki.js
2) I couldn't get password checking on the dashboard to work. I checked on the console (command htpasswd -vb htpasswd_file user password) - the check passes. But the container [wikijs-traefik-1] returns "Authentication failed middlewareName=authtraefik@docker middlewareType=BasicAuth"

**Comment by dima-online** [comment]
Может по русски?

**Comment by heyvaldemar** [comment]
We can discuss it in the Russian-speaking communities on [Telegram](https://t.me/DevOpsCompass) or [Discord](https://discord.gg/HBTF9N5TKH). It'll be more convenient.
